local CommandNames = {
	set_lens = "VantageSetLens",
	clear_lens = "VantageClearLens",
	explain = "VantageExplain",
	question = "VantageQuestion",
	edit = "VantageEdit",
	annotate = "VantageAnnotate",
	annotation_clear = "VantageAnnotationClear",
	load_walkthrough = "VantageLoadWalkthrough",
	generate_walkthrough = "VantageGenerateWalkthrough",
	status = "VantageStatus",
	session_output = "VantageSessionOutput",
	search = "VantageSearch",
	cancel = "VantageCancel",
	agent_reset = "VantageAgentReset",
	debug_log = "VantageDebugLog",
	model = "VantageModel",
	output_to_buffer = "VantageOutputToBuffer",
	compose = "VantageCompose",
	compose_send = "VantageComposeSend",
	compose_clear = "VantageComposeClear",
	history = "VantageHistory",
	history_clear_workspace = "VantageHistoryClearWorkspace",
	history_clear_all = "VantageHistoryClearAll",
	monitor = "VantageMonitor",
	health = "VantageHealth",
}

CommandNames.all = {
	CommandNames.set_lens,
	CommandNames.clear_lens,
	CommandNames.explain,
	CommandNames.question,
	CommandNames.edit,
	CommandNames.annotate,
	CommandNames.annotation_clear,
	CommandNames.load_walkthrough,
	CommandNames.generate_walkthrough,
	CommandNames.status,
	CommandNames.session_output,
	CommandNames.search,
	CommandNames.cancel,
	CommandNames.agent_reset,
	CommandNames.debug_log,
	CommandNames.model,
	CommandNames.output_to_buffer,
	CommandNames.compose,
	CommandNames.compose_send,
	CommandNames.compose_clear,
	CommandNames.history,
	CommandNames.history_clear_workspace,
	CommandNames.history_clear_all,
	CommandNames.monitor,
	CommandNames.health,
}

return CommandNames
